### ISSUE TITLE
Model export issue

### ISSUE THREAD

**Issue by i4never** [facebookresearch/pytext#902]
Hi all.
There's some problem during exporting model. I tried example in doc, model.caffe2 and model.onnx generated normally. But when I train my own model, only model.pt generated. I tried export cmd but nothing generated with cmd exit "successfully".
## Steps to reproduce
  1. Train a model.``model.pt`` in current dir. No``./model.caffe2.predictor`` or ``model.onnx``
  2. Export using ``pytext export --output-path exported_model.c2 < config.json``. No error message & No exported model.

Here's the config:
```json
{
  "debug_path": "./model.debug",
  "export_caffe2_path": "./model.caffe2.predictor",
  "export_onnx_path": "./model.onnx",
  "export_torchscript_path": null,
  "load_snapshot_path": "./model.pt",
  "modules_save_dir": "./modules",
  "random_seed": null,
  "report_eval_results": true,
  "save_all_checkpoints": true,
  "save_module_checkpoints": true,
  "save_snapshot_path": "./model.pt",
  "task": {
    "PairwiseClassificationTask": {
      "data": {
        "Data": {
          "batcher": {
            "PoolingBatcher": {
              "eval_batch_size": 128,
              "pool_num_batches": 10000,
              "test_batch_size": 128,
              "train_batch_size": 128
            }
          },
          "in_memory": true,
          "sort_key": null,
          "source": {
            "TSVDataSource": {
              "column_mapping": {},
              "delimiter": "\t",
              "eval_filename": "../data/dev.tsv",
              "field_names": [
                "label",
                "text1",
                "text2"
              ],
              "test_filename": "../data/dev.tsv",
              "train_filename": "../data/dev.tsv"
            }
          }
        }
      },
      "metric_reporter": {
        "model_select_metric": "accuracy",
        "output_path": "/tmp/test_out.txt",
        "target_label": null,
        "text_column_names": [
          "label",
          "text1",
          "text2"
        ]
      },
      "model": {
        "PairwiseModel": {
          "decoder": {
            "freeze": false,
            "hidden_dims": [],
            "layer_norm": false,
            "load_path": null,
            "out_dim": null,
            "save_path": null,
            "shared_module_key": null
          },
          "embedding": {
            "embed_dim": 32,
            "embedding_init_range": null,
            "embedding_init_strategy": "random",
            "export_input_names": [
              "tokens_vals"
            ],
            "freeze": false,
            "load_path": null,
            "lowercase_tokens": true,
            "min_freq": 1,
            "mlp_layer_dims": [],
            "pretrained_embeddings_path": "",
            "save_path": null,
            "shared_module_key": null,
            "vocab_file": "",
            "vocab_from_all_data": false,
            "vocab_from_pretrained_embeddings": false,
            "vocab_from_train_data": true,
            "vocab_size": 0
          },
          "encode_relations": true,
          "inputs": {
            "labels": {
              "LabelTensorizer": {
                "allow_unknown": false,
                "column": "label",
                "label_vocab": null,
                "pad_in_vocab": false
              }
            },
            "tokens1": {
              "add_bos_token": false,
              "add_eos_token": false,
              "build_vocab": true,
              "column": "text1",
              "max_seq_len": null,
              "tokenizer": {
                "Tokenizer": {
                  "lowercase": true,
                  "split_regex": "\\s+"
                }
              },
              "use_eos_token_for_bos": false,
              "vocab_file": "",
              "vocab_file_size_limit": 0
            },
            "tokens2": {
              "add_bos_token": false,
              "add_eos_token": false,
              "build_vocab": true,
              "column": "text2",
              "max_seq_len": null,
              "tokenizer": {
                "Tokenizer": {
                  "lowercase": true,
                  "split_regex": "\\s+"
                }
              },
              "use_eos_token_for_bos": false,
              "vocab_file": "",
              "vocab_file_size_limit": 0
            }
          },
          "output_layer": {
            "freeze": false,
            "label_weights": null,
            "load_path": null,
            "loss": {
              "CrossEntropyLoss": {}
            },
            "save_path": null,
            "shared_module_key": null
          },
          "representation": {
            "DocNNRepresentation": {
              "cnn": {
                "kernel_num": 100,
                "kernel_sizes": [
                  3,
                  4
                ]
              },
              "dropout": 0.4,
              "freeze": false,
              "load_path": null,
              "save_path": null,
              "shared_module_key": null
            }
          },
          "shared_representations": true
        }
      },
      "trainer": {
        "do_eval": true,
        "early_stop_after": 0,
        "epochs": 10,
        "max_clip_norm": null,
        "num_accumulated_batches": 1,
        "num_batches_per_epoch": 0,
        "num_samples_to_log_progress": 1000,
        "optimizer": {
          "Adam": {
            "lr": 0.001,
            "weight_decay": 1e-05
          }
        },
        "report_train_metrics": true,
        "scheduler": null,
        "target_time_limit_seconds": null
      }
    }
  },
  "test_out_path": "./test_out.txt",
  "use_cuda_if_available": true,
  "use_deterministic_cudnn": false,
  "use_fp16": false,
  "use_tensorboard": true,
  "version": 12
}

```

I've checked ``/tmp``. I've tried delete path config and still no exported model under ``/tmp`` or current dir. Am I missing sth?

**Comment by hudeven** [comment]
@i4never thanks for reporting this issue! I'm working on a fix for it.

Root cause: caffe2_export() is not implemented for some models like PairwiseModel. https://github.com/facebookresearch/pytext/blob/af1d1dca4db373601c9dbb84dfb0767ed435a840/pytext/models/pair_classification_model.py#L103

**Comment by i4never** [comment]
So load model from config file using ``create_model`` is the only way. Am I right?
https://github.com/facebookresearch/pytext/blob/cbcaa37b3bb20dee7a6997ea847e50c488e56a57/tests/module_load_save_test.py#L63

**Comment by i4never** [comment]
Looking forward. Model could be exported to caffe2 and onnx is one of the great feature.

**Comment by puttkraidej** [comment]
I have similar issue too, but my task is SquadQATask

```

===Starting training...

Parameters: PyTextConfig:
    debug_path: /tmp/model.debug
    distributed_world_size: 1
    export_caffe2_path: /pytext_models/qna.predictor.c2
    export_onnx_path: /pytext_models/qna.predictor.onnx
    export_torchscript_path: None
    load_snapshot_path: 
    modules_save_dir: 
    random_seed: None
    report_eval_results: False
    save_all_checkpoints: False
    save_module_checkpoints: False
    save_snapshot_path: /pytext_models/qna.predictor.pt
    task: SquadQATask.Config:
        data: Data.Config:
            batcher: PoolingBatcher.Config:
                eval_batch_size: 16
                pool_num_batches: 10000
                test_batch_size: 16
                train_batch_size: 16
            in_memory: True
            sort_key: None
            source: SquadDataSource.Config:
                eval_filename: /data/dev-v2.0.json
                ignore_impossible: True
                test_filename: /dev-v2.0.json
                train_filename: /train-v2.0.json
        metric_reporter: SquadMetricReporter.Config:
            false_label: False
            ignore_impossible: True
            max_answer_length: 16
            n_best_size: 5
            output_path: /tmp/test_out.txt
            pep_format: False
        model: DrQAModel.Config:
            doc_rnn: StackedBidirectionalRNN.Config:
                bidirectional: True
                concat_layers: True
                dropout: 0.4
                freeze: False
                hidden_size: 32
                load_path: None
                num_layers: 1
                rnn_type: RnnType.LSTM
                save_path: None
                shared_module_key: None
            dropout: 0.4
            embedding: WordEmbedding.Config:
                embed_dim: 300
                embedding_init_range: None
                embedding_init_strategy: EmbedInitStrategy.RANDOM
                export_input_names: ['tokens_vals']
                freeze: False
                load_path: None
                lowercase_tokens: True
                min_freq: 1
                mlp_layer_dims: []
                padding_idx: None
                pretrained_embeddings_path: 
                save_path: None
                shared_module_key: None
                vocab_file: 
                vocab_from_all_data: False
                vocab_from_pretrained_embeddings: False
                vocab_from_train_data: True
                vocab_size: 0
            inputs: ModelInput:
                has_answer: LabelTensorizer.Config:
                    allow_unknown: False
                    column: has_answer
                    label_vocab: None
                    pad_in_vocab: False
                squad_input: SquadTensorizer.Config:
                    add_bos_token: False
                    add_eos_token: False
                    answer_starts_column: answer_starts
                    answers_column: answers
                    column: text
                    doc_column: doc
                    max_doc_seq_len: 256
                    max_ques_seq_len: 64
                    max_seq_len: None
                    ques_column: question
                    tokenizer: Tokenizer.Config:
                        lowercase: True
                        split_regex: \W+
                    use_eos_token_for_bos: False
                    vocab: VocabConfig:
                        build_from_data: True
                        size_from_data: 0
                        vocab_files: []
            output_layer: SquadOutputLayer.Config:
                false_label: False
                freeze: False
                has_answer_loss_weight: 0.5
                ignore_impossible: True
                load_path: None
                loss: CrossEntropyLoss.Config:
                pos_loss_weight: 0.5
                save_path: None
                shared_module_key: None
            ques_rnn: StackedBidirectionalRNN.Config:
                bidirectional: True
                concat_layers: True
                dropout: 0.4
                freeze: False
                hidden_size: 32
                load_path: None
                num_layers: 1
                rnn_type: RnnType.LSTM
                save_path: None
                shared_module_key: None
        trainer: TaskTrainer.Config:
            do_eval: True
            early_stop_after: 0
            epochs: 10
            max_clip_norm: None
            num_accumulated_batches: 1
            num_batches_per_epoch: None
            num_samples_to_log_progress: 1000
            optimizer: Adam.Config:
                eps: 1e-08
                lr: 0.001
                weight_decay: 1e-05
            report_train_metrics: True
            scheduler: None
            sparsifier: None
            target_time_limit_seconds: None
    test_out_path: /tmp/test_out.txt
    torchscript_quantize: False
    use_cuda_if_available: True
    use_deterministic_cudnn: False
    use_fp16: False
    use_tensorboard: True
    version: 14


    # for debug of GPU
    use_cuda_if_available: True
    device_id: 0
    world_size: 1
    torch.cuda.is_available(): True
    cuda.CUDA_ENABLED: True
    cuda.DISTRIBUTED_WORLD_SIZE: 1
    
# for debug of FP16: fp16_enabled=False
Num trainable parameters: 5571983
```

***I install pytext using `pip install pytext-nlp` (pytext-nlp==0.2.2)

I also tried using `pytext export --output-path qna.predictor.c2 < myconfig.json`,
turns out that nothing happen except this message
```
Install apex from https://github.com/NVIDIA/apex/.
No config file specified, reading from stdin
Exporting /pytext_models/qna.predictor.pt to caffe2 file: /pytext_models/qna.predictor.c2 and onnx file: /pytext_models/qna.predictor.onnx
Loading model from /media/datawow/harddrive8TB/qna/pytext_models/qna.predictor.pt...
Skipped initializing tensorizers since they are loaded from a previously saved state.
```
caffe2 and onnx models are still not found :(
